[Feat] 회원정보 조회 수정 및 회원탈퇴 기능 구현
codeStatesStudyProject/TravelPlanRepo pull request #54
Opened 2022-10-02 07:11 UTC by Grooomit

[Feat]

## Proposed Changes

- 
-
-

2022-10-02 15:19 UTC, hipopotamus requested changes

2022-10-02 15:19 UTC, hipopotamus commented on src/main/resources/application-local.yml
> +logTracer: true
이 로컬 설정 제가 깃 이그노어에 등록해서 안올라와야되는데 왜인지 같이 올라와져있네요.
로컬폴더에 깃 이그노어 한번 확인해보시고(맨 아래에다 적어놨습니다)
개인적인 정보 노출을 피하기 위해서라도 해당부분은 지우고 올려주시는게 승재님하테도 좋을것 같습니다.

2022-10-03 07:49 UTC, Grooomit commented on src/main/resources/application-local.yml
> +logTracer: true
그러게요.. 저도 gitignore 확앤해봤는데 잘 설정되어있네요..

2022-10-03 08:14 UTC, hipopotamus approved these changes

2022-10-03 08:14 UTC, hipopotamus commented on src/main/resources/application-local.yml
> +logTracer: true
확인했습니다~!

2022-10-03 14:48 UTC, kexxxon approved these changes

2022-10-04 12:45 UTC, merged