[Feat] GlobalExceptionAdvice 구현
codeStatesStudyProject/TravelPlanRepo pull request #55
Opened 2022-10-08 20:44 UTC by kexxxon

[Feat] [Test]

## Proposed Changes

- GlobalExceptionAdvice 구현 및 테스트
    - 모든 예외/에러 발생 시 처리할 수 있는 메서드 구현 및 테스트
    - 자세한 에러 메시지는 악용 소지가 있을 수 있기 때문에 간단하게 출력

2022-10-09 03:03 UTC, hipopotamus requested changes
GlobalExceptionAdvice를 테스트하는 방향으로 수정해주셨으면 합니다.

2022-10-09 03:03 UTC, hipopotamus commented on src/test/java/travelplanrepo/global/ExceptionTest.java
> +    }
작성하신 GlobalExceptionAdvice는 spring mvc에서 발생하는 에러를 처리해주는 것이기 때문에  이 테스트는 GlobalExceptionAdvice를 테스트한다고 보기는 어려울것 같습니다,,! 

api에 에러가나는 요청을 보낼때 GlobalExceptionAdvice가 잘 처리를 해서 알맞은  json 응답이 나오는지를 확인 해보아야 할 것 같습니다.

2022-10-09 18:39 UTC, kexxxon commented on src/test/java/travelplanrepo/global/ExceptionTest.java
> +    }
수정 반영해서 재커밋 했습니다. 확인 부탁드립니다!

2022-10-10 21:33 UTC, Grooomit approved these changes

2022-10-11 00:32 UTC, hipopotamus commented on src/test/java/travelplanrepo/global/ExceptionTest.java
> +    }
확인했습니다!

2022-10-11 00:33 UTC, hipopotamus approved these changes

2022-10-11 00:50 UTC, merged